baseURL = 'https://services.octabyte.io/'
languageCode = 'en-us'
enableRobotsTXT = true
title = 'OctaByte Services | Custom Web, Mobile & Software Development Company'

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

[params]
description = """OctaByte services is a leading software development company offering web development, mobile app development, CRM, POS, and custom software solutions. We build scalable, high-performance digital products to help your business grow from idea to deployment."""
keywords = "software development company, web development services, mobile app development, custom software development, CRM development, POS development, desktop software development, IT solutions company, scalable software solutions, enterprise software development, full stack development services, OctaByte, software house, digital solutions provider, business software development"
logo = "/image/octabyte-services.png"
favicon = "/images/favicon.ico"
cover = "/images/cover.jpeg"
email = "contact@octabyte.io"

[params.social]
facebook = "https://www.facebook.com/octabyte.io/"
twitter = "https://x.com/octabyte_io"
linkedin = "https://www.linkedin.com/company/octabyte-io"

[languages]

  [languages.en]
    languageName = "English"
    languageCode = "en"
    weight = 1
    title = 'OctaByte Services | Custom Web, Mobile & Software Development Company'
    
    [languages.en.params]
      description = """OctaByte services is a leading software development company offering web development, mobile app development, CRM, POS, and custom software solutions. We build scalable, high-performance digital products to help your business grow from idea to deployment."""
      keywords = "software development company, web development services, mobile app development, custom software development, CRM development, POS development, desktop software development, IT solutions company, scalable software solutions, enterprise software development, full stack development services, OctaByte, software house, digital solutions provider, business software development"


  [languages.de]
    languageName = "Deutsch"
    languageCode = "de"
    weight = 2
    title = "OctaByte Services | Webentwicklung, App-Entwicklung & Individuelle Softwarelösungen"
    
    [languages.de.params]
      description = """OctaByte Services ist ein führendes Softwareunternehmen für Webentwicklung, App-Entwicklung, CRM-, POS- und individuelle Softwarelösungen. Wir entwickeln skalierbare und leistungsstarke digitale Produkte, die Ihr Unternehmen von der Idee bis zur erfolgreichen Umsetzung wachsen lassen."""
      keywords = "Softwareunternehmen, Webentwicklung, App-Entwicklung, individuelle Softwareentwicklung, CRM-Entwicklung, POS-Software, Desktop-Software, IT-Dienstleister, skalierbare Softwarelösungen, Unternehmenssoftware, Full-Stack Entwicklung, Softwareagentur, digitale Lösungen, Business Software Entwicklung"

  [languages.fr]
    languageName = "Français"
    languageCode = "fr"
    weight = 3
    title = "Services OctaByte | Développement Web, Mobile & Logiciels Sur Mesure"

    [languages.fr.params]
      description = """OctaByte est une entreprise spécialisée dans le développement de logiciels sur mesure, offrant des services de création de sites web, d'applications mobiles, de CRM, de POS et de solutions personnalisées. Nous concevons des produits digitaux performants et évolutifs pour accompagner la croissance de votre entreprise, de l’idée jusqu’au déploiement."""
      keywords = "entreprise de développement logiciel, développement web, développement d'applications mobiles, logiciel sur mesure, développement CRM, développement POS, solutions logicielles, développement entreprise, solutions digitales, agence développement logiciel, OctaByte, société IT, développement full stack"
