baseURL = 'https://services.octabyte.io/'
languageCode = 'en-us'
enableRobotsTXT = true
title = 'OctaByte Services | Custom Web, Mobile & Software Development Company'

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

[params]
description = """OctaByte services is a leading software development company offering web development, mobile app development, CRM, POS, and custom software solutions. We build scalable, high-performance digital products to help your business grow from idea to deployment."""
keywords = "software development company, web development services, mobile app development, custom software development, CRM development, POS development, desktop software development, IT solutions company, scalable software solutions, enterprise software development, full stack development services, OctaByte, software house, digital solutions provider, business software development"
logo = "/image/octabyte-services.png"
favicon = "/images/favicon.ico"
cover = "/images/cover.jpeg"
email = "contact@octabyte.io"

[params.social]
facebook = "https://www.facebook.com/octabyte.io/"
twitter = "https://x.com/octabyte_io"
linkedin = "https://www.linkedin.com/company/octabyte-io"

[languages]

  [languages.en]
    languageName = "English"
    languageCode = "en"
    weight = 1
    title = 'OctaByte Services | Custom Web, Mobile & Software Development Company'
    
    [languages.en.params]
      description = """OctaByte services is a leading software development company offering web development, mobile app development, CRM, POS, and custom software solutions. We build scalable, high-performance digital products to help your business grow from idea to deployment."""
      keywords = "software development company, web development services, mobile app development, custom software development, CRM development, POS development, desktop software development, IT solutions company, scalable software solutions, enterprise software development, full stack development services, OctaByte, software house, digital solutions provider, business software development"


  [languages.de]
    languageName = "Deutsch"
    languageCode = "de"
    weight = 2
    title = 'Deutsch title'

  [languages.fr]
    languageName = "Français"
    languageCode = "fr"
    weight = 3
